FROM python:3.11-slim

WORKDIR /backend/src

# 2) instale as deps
RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean
COPY requirements.txt ../
RUN pip install --no-cache-dir -r ../requirements.txt

COPY ./src .
COPY ../entrypoint.sh /backend/entrypoint.sh

ENV PYTHONPATH=/backend/src

ENTRYPOINT ["/backend/entrypoint.sh"]