FROM python:3.11-slim


WORKDIR /backend/src

# 2) instale as deps
RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean
COPY requirements.txt ../
RUN pip install --no-cache-dir -r ../requirements.txt

# 3) copie a pasta inteira src/ para /backend/src
COPY ./src .
COPY ./entrypoint.sh /backend/entrypoint.sh
RUN chmod +x /backend/entrypoint.sh

# 4) (opcional) você não precisa setar PYTHONPATH,
#    pois o cwd (/backend) já estará em sys.path
ENV PYTHONPATH=/backend/src

ENTRYPOINT ["/backend/entrypoint.sh"]